### ISSUE TITLE
Plugin not working with the "All Users" installation mode of Resharper.

### ISSUE THREAD

**Issue by marcelmunarolo** [xunit/resharper-xunit#67] opened 2015-07-16 20:58 UTC
Dear Colleagues,

Same issue as described in
https://github.com/xunit/resharper-xunit/issues/62

We have acquired some licenses for our company, and performed the installations with the "All User" options (since we are not local Adms and the installation is performed by the Help Desk team).

I am looking forward to see how we could make it work.
Thank You,
Marcel

**Comment by citizenmatt** [comment] 2015-07-20 22:39
Closing this issue as it's a duplicate of #62, and it requires an update to ReSharper, and can't be fixed via the plugin. I believe the issue will be fixed in 9.2. Alternatively, a normal per-user installation is required.

**Closed by citizenmatt** 2015-07-20 22:39 UTC
