### ISSUE TITLE
Resharper naming style for test methods isn't applied

### ISSUE THREAD

**Issue by oryol** [xunit/resharper-xunit#74] opened 2015-08-25 13:06 UTC
Resharper naming settings for "Test Method (Property)" isn't applied for xUnit test methods (with FactAttribute). Runner itself works fine.

http://develoq.net/2011/how-can-i-suppress-inconsistent-naming-inspection-just-for-test-files/ - example of such settings (it works with MsTest or NUnit, but doesn't work with xUnit).

**Comment by citizenmatt** [comment] 2015-09-07 16:04
I've just tested this and can't reproduce it - if I add a new rule for "Test Method (property)", and set it to e.g. ALL_UPPER, then my xunit test methods get flagged as violating the naming policy.

Can you provide an example where it's not working, please?

**Comment by citizenmatt** [comment] 2015-11-01 20:39
Closing this as not reproduced. Please reopen if you can get me a repro.

**Closed by citizenmatt** 2015-11-01 20:39 UTC

**Comment by philmh-isams** [comment] 2016-04-19 15:06
I am getting this issue using:
JetBrains ReSharper Ultimate 10.0.2 Build 104.0.20151218.120627
ReSharper 10.0.20151218.130009
in:
MS Visual Studio 14.0.23107.0.D14REL

I do have a Master file and then at the team shared level I set this Naming Style override and it is trying to apply the style defined at the master. If I add "Method" then my Naming Style override is picked up.

**Comment by citizenmatt** [comment] 2016-04-20 10:19
I'm not sure I follow - what's the "Master" file? What steps are you going through to try and get a custom naming style?

**Comment by philmh-isams** [comment] 2016-04-20 10:26
I have a file called "master" that is the base layer to my "team-shared" settings. In my "master" I have:
Code Editing > C# > Naming Style > Methods, properties and events = UpperCaseCamel
In my "team-shared" settings I have:
Code Editing > C# > Naming Style > Advanced settings... >
![image](https://cloud.githubusercontent.com/assets/15923770/14671657/e577f7b8-06ea-11e6-9288-fd3a9a779dca.png)

This rule is not being recognised as my xUnit Fact decorated public Test methods are having suggestions for methods named "it_should" to be "ItShould". If I change my extended Naming Style to include Methods as well as the test types and methods, it starts to work.

**Comment by citizenmatt** [comment] 2016-04-20 11:03
This could be a precedence issue with how the settings are being merged. Are there any other settings in the "master" file that might affect test methods, so the team shared settings are being overridden?

Could you share (post or email me direct - matt.ellis at jetbrains) your `.sln.dotSettings` file and the `master.dotSettings` file, please? That would give a clearer picture of what's going on.

**Comment by philmh-isams** [comment] 2016-04-20 12:28
Thanks Matt. I have e-mailed you and when, or if, we come up with a solution I will post it here. Thanks.

**Comment by citizenmatt** [comment] 2016-04-20 14:02
Everything looks fine in the settings files. I'm not sure what's going on. I've created a matching solution with the same files, and it works - the class and method names are underlined and I'm prompted to rename to `it_…`. However, when I first open the solution, only classes are highlighted. As soon as I edit the file, the methods are highlighted. I don't know why. Does this happen for you, too?

**Comment by philmh-isams** [comment] 2016-04-20 14:17
I have reset my personal solution settings, reset the "This computer" settings, and I still can't get the settings to work. It still prompts to change my Test methods to UpperCaseCamel.

As for your experience of it working on classes first and then methods, not even close for me.
Even applying the extended styling to the master is not working for me.

I think I know why - it's because my project is a DNX 4.5.1 and DNX Core 5.0 project.

**Comment by philmh-isams** [comment] 2016-04-20 14:33
Even applying the extended styling to the master is not working for me.

**Comment by philmh-isams** [comment] 2016-04-20 16:45
I managed to get it working with a standard Test project project with a mix of TestMethod, Fact and no attribute.

However, my Test project is in fact a DNX project, so I have attached an example.
[UnitTestSolution.zip](https://github.com/xunit/resharper-xunit/files/228384/UnitTestSolution.zip)

**Comment by citizenmatt** [comment] 2016-04-21 09:24
Aha. That's it. Looks like there's a bug in identifying unit test elements in DNX projects. For example, if you open the File Structure window for the standard unit test project, the test classes and methods are marked as tests, while doing the same in the DNX project, the test classes and methods are just marked as normal classes + methods.

I've created an issue to get this fixed in ReSharper - [RSRP-458406](https://youtrack.jetbrains.com/issue/RSRP-458406). Thanks for narrowing it down!

**Comment by philmh-isams** [comment] 2016-04-21 09:35
Ah. Glad the attached project highlighted the issue perfectly and I was not going insane.
Thanks for logging it.
