### ISSUE TITLE
Not working for .NET Core

### ISSUE THREAD

**Issue by SuperJMN** [xunit/resharper-xunit#124] opened 2016-07-01 15:30 UTC
Yes, it's true that the only versions of ReSharper that can handle .NET Core property are EAPs, but you could make the xUnit extension run with them before the official release :P

I'm missing it so much.

**Comment by citizenmatt** [comment] 2016-07-04 13:29
Duplicate of #38. Don't worry, it's coming.

**Closed as completed by citizenmatt** 2016-07-04 13:29 UTC
