### ISSUE TITLE
After 2016.2 Update, discovering xUnit Theory tests causes White Screen when selecting large blocks that need to be discovered

### ISSUE THREAD

**Issue by ChrisReddickClarity** [xunit/resharper-xunit#127] opened 2016-09-09 21:43 UTC
This issue was originally posted to the R# YouTrack, but it appears this is a far more active method of reporting bugs.
See: https://youtrack.jetbrains.com/issue/RSRP-460511
This issue is extremely similar: https://youtrack.jetbrains.com/issue/RSRP-381235

I have about 6k tests counted when all tests are discovered, about half that when it first loads. If I select more than a few Categories of "undiscovered" tests at a time to run (usually OK at 6, gets worse to untenable at 8+) I start seeing the White Screen of Death for extended periods. During the parts where the count gets updated in the UI, which is rare on large groups, I'm hovering over the abort button hoping to catch it so I can select a smaller group and try again. If it's real bad, I doesn't come back at all and I have to kill it with the Task Manager.

I've only tried it once but I saw that once discovered, I could select all and run again. Closing Visual Studio redoes the counts on it and I have to start over.

Visual Studio 2015 Update 3
ReSharper 2016.2
Windows 10

Update: Definitely runs at full speed if all tests are already discovered. I can select the entire session to run at once at that point and they zip on through.

**Comment by citizenmatt** [comment] 2016-09-14 09:32
Hi. The YouTrack is definitely the right place to report this. It's clearly a performance issue in ReSharper itself, rather than the xunit support (that said, the xunit support is now also part of ReShaprer itself). The issue is assigned to the developer responsible, so he's already aware of the problem. I'll see if I can get an update, although any update would likely be a part of 2016.3.

One thing that would be useful is [to profile Visual Studio](https://resharper-support.jetbrains.com/hc/en-us/articles/207243205) while it's going wrong. Some more details on the tests would be helpful, too - are they all theories?

**Closed as completed by citizenmatt** 2016-09-14 09:32 UTC
